local M = {}

---@param colors table
---@param config ThemeConfig
---@return table<string, HighlightDefinition>
function M.get(colors, config)
  return {
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.secondary, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.secondary_active },
    CursorLineNr = { fg = colors.primary_soft, bg = colors.bg1 },
    NonText = { link = "ThemeBg2" },
    SpecialKey = { link = "ThemeFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.primary_soft, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.primary_active, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "ThemePrimaryMuted" },
    Underlined = { fg = colors.secondary_active, underline = config.underline },
    StatusLine = { fg = colors.fg1, bg = colors.bg2 },
    StatusLineNC = { fg = colors.fg4, bg = colors.bg1 },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.secondary_active, bg = colors.bg2, bold = config.bold },
    Directory = { link = "ThemeSecondaryBold" },
    Title = { link = "ThemeSecondaryBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.primary, bold = config.bold },
    MoreMsg = { link = "ThemePrimarySoftBold" },
    ModeMsg = { link = "ThemePrimarySoftBold" },
    Question = { link = "ThemePrimaryActiveBold" },
    WarningMsg = { link = "ThemePrimaryBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { fg = colors.muted, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.muted, bg = nil } or { fg = colors.muted, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.secondary_active, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.diff_delete },
    DiffAdd = { bg = colors.diff_add },
    DiffChange = { bg = colors.diff_change },
    DiffText = { bg = colors.primary_soft, fg = colors.bg0 },
    SpellCap = { link = "ThemeSecondaryActiveUnderline" },
    SpellBad = { link = "ThemePrimaryUnderline" },
    SpellLocal = { link = "ThemeSecondarySoftUnderline" },
    SpellRare = { link = "ThemePrimaryMutedUnderline" },
    Whitespace = { fg = colors.bg2 },
    EndOfBuffer = { link = "NonText" },
  }
end

return M
