local M = {}

---@param colors table
---@param config ThemeConfig
---@return table<string, HighlightDefinition>
function M.get(colors, config)
  return {
    -- Blink Cmp
    BlinkCmpLabel = { link = "ThemeFg0" },
    BlinkCmpLabelDeprecated = { link = "ThemeFg1" },
    BlinkCmpLabelMatch = { link = "ThemeSecondaryActiveBold" },
    BlinkCmpLabelDetail = { link = "ThemeGray" },
    BlinkCmpLabelDescription = { link = "ThemeGray" },
    BlinkCmpKindText = { link = "ThemePrimaryActive" },
    BlinkCmpKindVariable = { link = "ThemePrimaryActive" },
    BlinkCmpKindMethod = { link = "ThemeSecondaryActive" },
    BlinkCmpKindFunction = { link = "ThemeSecondaryActive" },
    BlinkCmpKindConstructor = { link = "ThemePrimarySoft" },
    BlinkCmpKindUnit = { link = "ThemeSecondaryActive" },
    BlinkCmpKindField = { link = "ThemeSecondaryActive" },
    BlinkCmpKindClass = { link = "ThemePrimarySoft" },
    BlinkCmpKindInterface = { link = "ThemePrimarySoft" },
    BlinkCmpKindModule = { link = "ThemeSecondaryActive" },
    BlinkCmpKindProperty = { link = "ThemeSecondaryActive" },
    BlinkCmpKindValue = { link = "ThemePrimaryActive" },
    BlinkCmpKindEnum = { link = "ThemePrimarySoft" },
    BlinkCmpKindOperator = { link = "ThemePrimarySoft" },
    BlinkCmpKindKeyword = { link = "ThemePrimaryMuted" },
    BlinkCmpKindEvent = { link = "ThemePrimaryMuted" },
    BlinkCmpKindReference = { link = "ThemePrimaryMuted" },
    BlinkCmpKindColor = { link = "ThemePrimaryMuted" },
    BlinkCmpKindSnippet = { link = "ThemeSecondary" },
    BlinkCmpKindFile = { link = "ThemeSecondaryActive" },
    BlinkCmpKindFolder = { link = "ThemeSecondaryActive" },
    BlinkCmpKindEnumMember = { link = "ThemeSecondarySoft" },
    BlinkCmpKindConstant = { link = "ThemePrimaryActive" },
    BlinkCmpKindStruct = { link = "ThemePrimarySoft" },
    BlinkCmpKindTypeParameter = { link = "ThemePrimarySoft" },
    BlinkCmpSource = { link = "ThemeGray" },
    BlinkCmpGhostText = { link = "ThemeBg4" },
    -- nvim-cmp
    CmpItemAbbr = { link = "ThemeFg0" },
    CmpItemAbbrDeprecated = { link = "ThemeFg1" },
    CmpItemAbbrMatch = { link = "ThemeSecondaryActiveBold" },
    CmpItemAbbrMatchFuzzy = { link = "ThemeSecondaryActiveUnderline" },
    CmpItemMenu = { link = "ThemeGray" },
    CmpItemKindText = { link = "ThemePrimaryActive" },
    CmpItemKindVariable = { link = "ThemePrimaryActive" },
    CmpItemKindMethod = { link = "ThemeSecondaryActive" },
    CmpItemKindFunction = { link = "ThemeSecondaryActive" },
    CmpItemKindConstructor = { link = "ThemePrimarySoft" },
    CmpItemKindUnit = { link = "ThemeSecondaryActive" },
    CmpItemKindField = { link = "ThemeSecondaryActive" },
    CmpItemKindClass = { link = "ThemePrimarySoft" },
    CmpItemKindInterface = { link = "ThemePrimarySoft" },
    CmpItemKindModule = { link = "ThemeSecondaryActive" },
    CmpItemKindProperty = { link = "ThemeSecondaryActive" },
    CmpItemKindValue = { link = "ThemePrimaryActive" },
    CmpItemKindEnum = { link = "ThemePrimarySoft" },
    CmpItemKindOperator = { link = "ThemePrimarySoft" },
    CmpItemKindKeyword = { link = "ThemePrimaryMuted" },
    CmpItemKindEvent = { link = "ThemePrimaryMuted" },
    CmpItemKindReference = { link = "ThemePrimaryMuted" },
    CmpItemKindColor = { link = "ThemePrimaryMuted" },
    CmpItemKindSnippet = { link = "ThemeSecondary" },
    CmpItemKindFile = { link = "ThemeSecondaryActive" },
    CmpItemKindFolder = { link = "ThemeSecondaryActive" },
    CmpItemKindEnumMember = { link = "ThemeSecondarySoft" },
    CmpItemKindConstant = { link = "ThemePrimaryActive" },
    CmpItemKindStruct = { link = "ThemePrimarySoft" },
    CmpItemKindTypeParameter = { link = "ThemePrimarySoft" },
  }
end

return M
