local M = {}

---@param colors table
---@param config ThemeConfig
---@return table<string, HighlightDefinition>
function M.get(colors, config)
  return {
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { link = "ThemeSecondary" },
    MiniDepsChangeRemoved = { link = "ThemePrimary" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { link = "ThemeSecondary" },
    MiniDiffSignChange = { link = "ThemeSecondarySoft" },
    MiniDiffSignDelete = { link = "ThemePrimary" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { bg = colors.bg2 },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { link = "ThemeFg1" },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { link = "ThemePrimaryActiveBold" },
    MiniHipatternsFixme = { fg = colors.bg0, bg = colors.primary, bold = config.bold },
    MiniHipatternsHack = { fg = colors.bg0, bg = colors.primary_soft, bold = config.bold },
    MiniHipatternsNote = { fg = colors.bg0, bg = colors.secondary_active, bold = config.bold },
    MiniHipatternsTodo = { fg = colors.bg0, bg = colors.secondary_soft, bold = config.bold },
    MiniIconsAzure = { link = "ThemeSecondaryActive" },
    MiniIconsBlue = { link = "ThemeSecondaryActive" },
    MiniIconsCyan = { link = "ThemeSecondarySoft" },
    MiniIconsGreen = { link = "ThemeSecondary" },
    MiniIconsGrey = { link = "ThemeFg0" },
    MiniIconsOrange = { link = "ThemePrimaryActive" },
    MiniIconsPurple = { link = "ThemePrimaryMuted" },
    MiniIconsRed = { link = "ThemePrimary" },
    MiniIconsYellow = { link = "ThemePrimarySoft" },
    MiniIndentscopeSymbol = { link = "ThemeGray" },
    MiniIndentscopeSymbolOff = { link = "ThemePrimarySoft" },
    MiniJump = { link = "ThemePrimaryActiveUnderline" },
    MiniJump2dDim = { link = "ThemeGray" },
    MiniJump2dSpot = { fg = colors.primary_active, bold = config.bold, nocombine = true },
    MiniJump2dSpotAhead = { fg = colors.secondary_soft, bg = colors.bg0, nocombine = true },
    MiniJump2dSpotUnique = { fg = colors.primary_soft, bold = config.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { bg = colors.bg2 },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { link = "ThemeGray" },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterSection = { link = "Delimiter" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { link = "StatusLine" },
    MiniStatuslineFileinfo = { link = "StatusLine" },
    MiniStatuslineFilename = { link = "StatusLineNC" },
    MiniStatuslineInactive = { link = "StatusLineNC" },
    MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.primary_soft, bold = config.bold, nocombine = true },
    MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.secondary_active, bold = config.bold, nocombine = true },
    MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold, nocombine = true },
    MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.secondary_soft, bold = config.bold, nocombine = true },
    MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.primary, bold = config.bold, nocombine = true },
    MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.secondary, bold = config.bold, nocombine = true },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = colors.secondary, bg = colors.bg1, bold = config.bold, reverse = config.invert_tabline },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    MiniTablineModifiedCurrent = {
      fg = colors.bg1,
      bg = colors.secondary,
      bold = config.bold,
      reverse = config.invert_tabline,
    },
    MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
    MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },
    MiniTestEmphasis = { bold = config.bold },
    MiniTestFail = { link = "ThemePrimaryBold" },
    MiniTestPass = { link = "ThemeSecondaryBold" },
    MiniTrailspace = { bg = colors.primary },
  }
end

return M
